print("Hi, my name is Sanay")
print("I am 12 years old")
print("I study in 7th grade")
print("I do coding as an extracirricular activity")
print("I study in Caelum High School")
print("I am in Aquila house")
print("I swim as a sport")
print("I live in INDIA")
print("I have won 8 gold medals and 3 silver medals")
print("I love watching cricket")
print("I especially like to watch IPL")
print("The full form for IPL is Indian Premier League")
print("My favourite team is the Mumbai Indians")
print("In the Mumbai Indians, my favourite batsman is Surya Kumar Yadav🏏🏏🏏🏏")
print("Surya Kumar Yadav is nicknamed SKY")
print("My favourite bowler in the Mumbai Indians is Jasprit Bumrah🏏🏏🏏🏏")
print("The number of IPL trophies they(Mumbai Indians) have won is 1+1+1+1+1 🏆+🏆+🏆+🏆+🏆" 1+1+1+1+1)
print("My favourite subject is mathematics.")
print("Here is a trick question, what is 22 divided by 7" 22/7)
print("The answer is : it is called pi, and is an infinite number. The longest known value was found by Rajveer Meena who got upto 70,000 digits 🫨🤯😮!!!")